export enum EIconNameTypes {
  plus = 'plus',
  notification = 'notification',
  close = 'close',
  delete = 'delete',
  edit = 'edit',
  'folder-view' = 'folder-view',
  calendar = 'calendar',
  search = 'search',
  up = 'up',
  down = 'down',
  left = 'left',
  right = 'right',
  eye = 'eye',
  'eye-invisible' = 'eye-invisible',
  user = 'user',
  unlock = 'unlock',
  project = 'project',
}
